### ISSUE TITLE
Java 9 support appears to be broken

### ISSUE THREAD

**Issue by kyegupov** [palantir/gradle-docker#154] opened 2017-12-11 15:15 UTC
On openjdk 9~b181-4 the error is:
```
Could not create an instance of type com.palantir.gradle.docker.DockerExtension_Decorated.
```

On Oracle JDK 9.0.1, the error is:
```
java.lang.IllegalArgumentException: Could not determine java version from '9.0.1'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
```

**Comment by tmccarthy** [comment] 2017-12-13 03:48
Looks like this is a bug in Gradle. Their ticket is [here](https://github.com/gradle/gradle/issues/2992). Looks like it was fixed in Gradle 4.2.1.

**Comment by kyegupov** [comment] 2017-12-16 20:07
See https://github.com/palantir/gradle-docker/pull/157

**Comment by pkoenig10** [comment] 2018-03-24 23:07
Confirmed that the latest version works on Java 9.

**Closed as completed by pkoenig10** 2018-03-24 23:07 UTC
